// bordercore/front-end/vue/common/RelatedObjects.vue
<template>
    <div v-if="objectList.length > 0 || showEmptyList" class="hover-reveal-target mb-3">
        <transition :name="transitionName">
            <card class="position-relative h-100 backdrop-filter z-index-positive">
                <template #title-slot>
                    <div class="d-flex">
                        <div class="card-title d-flex">
                            <font-awesome-icon icon="bookmark" class="text-primary me-3 mt-1" />
                            {{ title }}
                        </div>
                        <div class="dropdown-menu-container ms-auto">
                            <drop-down-menu class="d-none hover-reveal-object" :show-on-hover="false">
                                <template #dropdown>
                                    <li>
                                        <a class="dropdown-item" href="#" @click.prevent="openObjectSelectModal">
                                            <span>
                                                <font-awesome-icon icon="plus" class="text-primary me-3" />
                                            </span>
                                            New Object
                                        </a>
                                    </li>
                                </template>
                            </drop-down-menu>
                        </div>
                    </div>
                </template>

                <template #content>
                    <hr class="divider">
                    <ul class="list-group list-group-flush interior-borders">
                        <slick-list
                            v-model:list="objectList"
                            :distance="3"
                            helper-class="slicklist-helper"
                            @sort-end="handleSort"
                        >
                            <slick-item
                                v-for="(element, index) in objectList"
                                :key="element.uuid"
                                :index="index"
                                class="slicklist-item"
                                :style="'z-index: ' + (1000 - index)"
                            >
                                <div class="slicklist-list-item-inner">
                                    <li v-cloak :key="element.uuid" class="hover-target list-group-item list-group-item-secondary px-0" :data-uuid="element.uuid">
                                        <div class="dropdown-height d-flex align-items-start">
                                            <div class="d-flex flex-column">
                                                <div v-if="element.type === 'bookmark'" class="pe-2">
                                                    <img
                                                        :src="element.cover_url"
                                                        width="120"
                                                        height="67"
                                                        data-bs-toggle="popover"
                                                        :data-bs-html="true"
                                                        data-bs-placement="right"
                                                        data-bs-trigger="hover"
                                                        :data-bs-delay="1000"
                                                        :data-bs-content="`<img src='${element.cover_url_large}' />`"
                                                    >
                                                </div>
                                                <div v-else-if="element.type === 'blob'" class="pe-2">
                                                    <img :src="element.cover_url">
                                                </div>
                                                <div>
                                                    <a :href="element.url">{{ element.name }}</a>
                                                </div>
                                                <Transition name="fade" mode="out-in" @after-enter="handleInputTransition">
                                                    <div v-if="!element.noteIsEditable" class="node-object-note" @click="element.noteIsEditable = true">
                                                        {{ element.note }}
                                                    </div>
                                                    <div v-else>
                                                        <input ref="input" type="text" class="form-control form-control-sm" :value="element.note" placeholder="" autocomplete="off" @blur="handleEditNote(element, $event.target.value)" @keydown.enter="handleEditNote(element, $event.target.value)">
                                                    </div>
                                                </Transition>
                                            </div>
                                            <drop-down-menu :show-on-hover="true">
                                                <template #dropdown>
                                                    <li>
                                                        <a class="dropdown-item" href="#" @click.prevent="handleRemoveObject(element)">
                                                            <font-awesome-icon icon="trash-alt" class="text-primary me-3" />Remove
                                                        </a>
                                                        <a class="dropdown-item" :href="element.edit_url">
                                                            <font-awesome-icon icon="pencil-alt" class="text-primary me-3" />Edit <span>{{ element.type }}</span>
                                                        </a>
                                                        <a class="dropdown-item" href="#" @click.prevent="element.noteIsEditable = true">
                                                            <font-awesome-icon :icon="element.note ? 'pencil-alt' : 'plus'" class="text-primary me-3" />{{ element.note ? 'Edit' : 'New' }} note
                                                        </a>
                                                    </li>
                                                </template>
                                            </drop-down-menu>
                                        </div>
                                    </li>
                                </div>
                            </slick-item>
                        </slick-list>
                        <div v-cloak v-if="objectList.length == 0" :key="1" class="text-muted">
                            No related objects
                        </div>
                    </ul>
                </template>
            </card>
        </transition>
    </div>
</template>

<script>

    import Card from "/front-end/vue/common/Card.vue";
    import DropDownMenu from "/front-end/vue/common/DropDownMenu.vue";
    import {FontAwesomeIcon} from "@fortawesome/vue-fontawesome";
    import {SlickList, SlickItem} from "vue-slicksort";

    export default {
        components: {
            Card,
            DropDownMenu,
            FontAwesomeIcon,
            SlickItem,
            SlickList,
        },
        props: {
            objectUuid: {
                default: "",
                type: String,
            },
            title: {
                default: "Related Objects",
                type: String,
            },
            nodeType: {
                default: "blob",
                type: String,
            },
            relatedObjectsUrl: {
                default: "",
                type: String,
            },
            newObjectUrl: {
                default: "",
                type: String,
            },
            removeObjectUrl: {
                default: "",
                type: String,
            },
            sortRelatedObjectsUrl: {
                default: "url",
                type: String,
            },
            editRelatedObjectNoteUrl: {
                default: "url",
                type: String,
            },
            transitionName: {
                default: "fade",
                type: String,
            },
            showEmptyList: {
                default: true,
                type: Boolean,
            },
            isNew: {
                default: false,
                type: Boolean,
            },
        },
        emits: ["open-object-select-modal"],
        setup(props, ctx) {
            const input = ref(null);
            const objectList = ref([]);

            function newObject(bcObject) {
                if (props.isNew) {
                    objectList.value.push(bcObject);
                    return;
                }

                doPost(
                    props.newObjectUrl,
                    {
                        "node_uuid": props.objectUuid,
                        "object_uuid": bcObject.uuid,
                        "node_type": props.nodeType,
                    },
                    (response) => {
                        getRelatedObjects();
                    },
                    "Object added",
                );
            };

            function getRelatedObjects() {
                doGet(
                    props.relatedObjectsUrl.replace(/00000000-0000-0000-0000-000000000000/, props.objectUuid),
                    (response) => {
                        objectList.value = response.data.related_objects;
                        nextTick(() => {
                            const popoverTriggerList = document.querySelectorAll("[data-bs-toggle='popover']");
                            [...popoverTriggerList].map((popoverTriggerEl) => new Popover(popoverTriggerEl));
                        });
                    },
                    "Error getting related objects",
                );
            };

            function handleEditNote(bcObject, note) {
                bcObject.noteIsEditable = false;

                // If the note hasn't changed, abort
                if (note == bcObject.note) {
                    return;
                }

                bcObject.note = note;
                doPost(
                    props.editRelatedObjectNoteUrl,
                    {
                        "node_uuid": props.objectUuid,
                        "object_uuid": bcObject.uuid,
                        "note": note,
                        "node_type": props.nodeType,
                    },
                    (response) => {
                        getRelatedObjects();
                    },
                );
            };

            function handleInputTransition(evt) {
                const input = evt.querySelector("input");
                if (input) {
                    input.focus();
                }
            };

            function handleRemoveObject(bcObject) {
                if (props.isNew) {
                    const newObjectList = objectList.value.filter((x) => x.uuid !== bcObject.uuid);
                    objectList.value = newObjectList;
                    return;
                }

                doPost(
                    props.removeObjectUrl,
                    {
                        "node_uuid": props.objectUuid,
                        "object_uuid": bcObject.uuid,
                        "node_type": props.nodeType,
                    },
                    (response) => {
                        getRelatedObjects();
                    },
                    "Object removed",
                );
            };

            function handleSort(event) {
                if (event.oldIndex === event.newIndex) {
                    return;
                }
                const blobUuid = objectList.value[event.oldIndex].uuid;
                // The backend expects the ordering to begin with 1, not 0, so add 1.
                const newPosition = event.newIndex + 1;

                if (props.isNew) {
                    return;
                }

                doPost(
                    props.sortRelatedObjectsUrl,
                    {
                        "node_uuid": props.objectUuid,
                        "object_uuid": blobUuid,
                        "new_position": newPosition,
                        "node_type": props.nodeType,
                    },
                    () => {},
                );
            };

            function openObjectSelectModal() {
                ctx.emit("open-object-select-modal");
            };

            onMounted(() => {
                if (!props.isNew) {
                    getRelatedObjects();
                }
            });

            return {
                newObject,
                input,
                objectList,
                handleEditNote,
                handleInputTransition,
                handleRemoveObject,
                handleSort,
                openObjectSelectModal,
            };
        },
    };

</script>

// bordercore/front-end/react/common/RelatedObjects.tsx
import React, {
  useState,
  useEffect,
  useCallback,
  useRef,
  useImperativeHandle,
  forwardRef,
} from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faBookmark, faPlus, faTrashAlt, faPencilAlt } from "@fortawesome/free-solid-svg-icons";
import {
  DndContext,
  closestCenter,
  KeyboardSensor,
  PointerSensor,
  useSensor,
  useSensors,
  DragEndEvent,
} from "@dnd-kit/core";
import {
  arrayMove,
  SortableContext,
  sortableKeyboardCoordinates,
  verticalListSortingStrategy,
  useSortable,
} from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import Card from "./Card";
import DropDownMenu from "./DropDownMenu";
import { doGet, doPost } from "../utils/reactUtils";

interface RelatedObject {
  uuid: string;
  name: string;
  url: string;
  edit_url: string;
  type: string;
  cover_url?: string;
  cover_url_large?: string;
  note?: string;
  noteIsEditable?: boolean;
}

interface RelatedObjectsProps {
  objectUuid: string;
  title?: string;
  nodeType?: string;
  relatedObjectsUrl: string;
  newObjectUrl: string;
  removeObjectUrl: string;
  sortRelatedObjectsUrl: string;
  editRelatedObjectNoteUrl: string;
  searchNamesUrl: string;
  showEmptyList?: boolean;
  onOpenObjectSelectModal?: () => void;
}

export interface RelatedObjectsHandle {
  refresh: () => void;
}

export const RelatedObjects = forwardRef<RelatedObjectsHandle, RelatedObjectsProps>(
  function RelatedObjects(
    {
      objectUuid,
      title = "Related Objects",
      nodeType = "drill",
      relatedObjectsUrl,
      newObjectUrl,
      removeObjectUrl,
      sortRelatedObjectsUrl,
      editRelatedObjectNoteUrl,
      searchNamesUrl,
      showEmptyList = true,
      onOpenObjectSelectModal,
    },
    ref
  ) {
    const [objectList, setObjectList] = useState<RelatedObject[]>([]);
    const [dataLoading, setDataLoading] = useState(true);
    const inputRefs = useRef<{ [key: string]: HTMLInputElement | null }>({});

    const sensors = useSensors(
      useSensor(PointerSensor),
      useSensor(KeyboardSensor, {
        coordinateGetter: sortableKeyboardCoordinates,
      })
    );

    const getRelatedObjects = useCallback(() => {
      doGet(
        relatedObjectsUrl,
        (response: any) => {
          setObjectList(response.data.related_objects || []);
          setDataLoading(false);
        },
        "Error getting related objects"
      );
    }, [relatedObjectsUrl]);

    useImperativeHandle(
      ref,
      () => ({
        refresh: getRelatedObjects,
      }),
      [getRelatedObjects]
    );

    useEffect(() => {
      getRelatedObjects();
    }, [getRelatedObjects]);

    const handleRemoveObject = useCallback(
      (bcObject: RelatedObject) => {
        doPost(
          removeObjectUrl,
          {
            node_uuid: objectUuid,
            object_uuid: bcObject.uuid,
            node_type: nodeType,
          },
          () => {
            getRelatedObjects();
          }
        );
      },
      [removeObjectUrl, objectUuid, nodeType, getRelatedObjects]
    );

    const handleEditNote = useCallback(
      (bcObject: RelatedObject, note: string) => {
        // Update local state to hide input
        setObjectList(prev =>
          prev.map(obj => (obj.uuid === bcObject.uuid ? { ...obj, noteIsEditable: false } : obj))
        );

        // If the note hasn't changed, abort
        if (note === bcObject.note) {
          return;
        }

        doPost(
          editRelatedObjectNoteUrl,
          {
            node_uuid: objectUuid,
            object_uuid: bcObject.uuid,
            note: note,
            node_type: nodeType,
          },
          () => {
            getRelatedObjects();
          }
        );
      },
      [editRelatedObjectNoteUrl, objectUuid, nodeType, getRelatedObjects]
    );

    const toggleNoteEditable = useCallback((uuid: string, editable: boolean) => {
      setObjectList(prev =>
        prev.map(obj => (obj.uuid === uuid ? { ...obj, noteIsEditable: editable } : obj))
      );
      if (editable) {
        setTimeout(() => {
          inputRefs.current[uuid]?.focus();
        }, 50);
      }
    }, []);

    const handleDragEnd = useCallback(
      (event: DragEndEvent) => {
        const { active, over } = event;

        if (over && active.id !== over.id) {
          const oldIndex = objectList.findIndex(item => item.uuid === active.id);
          const newIndex = objectList.findIndex(item => item.uuid === over.id);

          const newList = arrayMove(objectList, oldIndex, newIndex);
          setObjectList(newList);

          const newPosition = newIndex + 1;

          doPost(
            sortRelatedObjectsUrl,
            {
              node_uuid: objectUuid,
              object_uuid: active.id as string,
              new_position: newPosition,
              node_type: nodeType,
            },
            () => {}
          );
        }
      },
      [objectList, sortRelatedObjectsUrl, objectUuid, nodeType]
    );

    const openModal = useCallback(() => {
      onOpenObjectSelectModal?.();
    }, [onOpenObjectSelectModal]);

    if (!showEmptyList && objectList.length === 0 && !dataLoading) {
      return null;
    }

    const titleSlot = (
      <div className="d-flex">
        <div className="card-title d-flex">
          <FontAwesomeIcon icon={faBookmark} className="text-primary me-3 mt-1" />
          {title}
        </div>
        <div className="dropdown-menu-container ms-auto">
          <DropDownMenu
            showOnHover={false}
            dropdownSlot={
              <ul className="dropdown-menu-list">
                <li key="new-object">
                  <a
                    className="dropdown-item"
                    href="#"
                    onClick={e => {
                      e.preventDefault();
                      openModal();
                    }}
                  >
                    <FontAwesomeIcon icon={faPlus} className="text-primary me-3" />
                    New Object
                  </a>
                </li>
              </ul>
            }
          />
        </div>
      </div>
    );

    return (
      <Card
        className="backdrop-filter position-relative z-index-positive"
        cardClassName="mb-gutter"
        titleSlot={titleSlot}
      >
        <hr className="divider" />
        {dataLoading ? (
          <div className="text-secondary">Loading...</div>
        ) : objectList.length === 0 ? (
          <div className="text-muted">No related objects</div>
        ) : (
          <DndContext
            sensors={sensors}
            collisionDetection={closestCenter}
            onDragEnd={handleDragEnd}
          >
            <SortableContext
              items={objectList.map(item => item.uuid)}
              strategy={verticalListSortingStrategy}
            >
              <ul className="list-group list-group-flush interior-borders mb-0">
                {objectList.map((element, index) => (
                  <SortableRelatedObject
                    key={element.uuid}
                    element={element}
                    index={index}
                    inputRefs={inputRefs}
                    handleRemoveObject={handleRemoveObject}
                    handleEditNote={handleEditNote}
                    toggleNoteEditable={toggleNoteEditable}
                  />
                ))}
              </ul>
            </SortableContext>
          </DndContext>
        )}
      </Card>
    );
  }
);

export default RelatedObjects;

interface SortableRelatedObjectProps {
  element: RelatedObject;
  index: number;
  inputRefs: React.MutableRefObject<{ [key: string]: HTMLInputElement | null }>;
  handleRemoveObject: (bcObject: RelatedObject) => void;
  handleEditNote: (bcObject: RelatedObject, note: string) => void;
  toggleNoteEditable: (uuid: string, editable: boolean) => void;
}

function SortableRelatedObject({
  element,
  index,
  inputRefs,
  handleRemoveObject,
  handleEditNote,
  toggleNoteEditable,
}: SortableRelatedObjectProps) {
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({
    id: element.uuid,
  });

  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
    zIndex: isDragging ? 1001 : 1000 - index,
    position: "relative" as const,
  };

  return (
    <div
      ref={setNodeRef}
      style={style}
      className={`slicklist-item show-child-on-hover ${isDragging ? "dragging" : ""}`}
      {...attributes}
      {...listeners}
    >
      <div className="slicklist-list-item-inner">
        <li className="list-group-item list-group-item-secondary px-0">
          <div className="dropdown-height d-flex align-items-start">
            <div className="d-flex flex-column flex-grow-1">
              {element.type === "bookmark" && element.cover_url && (
                <div className="pe-2">
                  <img src={element.cover_url} width="120" height="67" alt="" />
                </div>
              )}
              {element.type === "blob" && element.cover_url && (
                <div className="pe-2">
                  <img src={element.cover_url} alt="" />
                </div>
              )}
              <div>
                <a href={element.url}>{element.name}</a>
              </div>
              {!element.noteIsEditable ? (
                <div
                  className="node-object-note text-muted small cursor-pointer"
                  onClick={() => toggleNoteEditable(element.uuid, true)}
                >
                  {element.note}
                </div>
              ) : (
                <div onPointerDown={e => e.stopPropagation()}>
                  <input
                    ref={el => {
                      inputRefs.current[element.uuid] = el;
                    }}
                    type="text"
                    className="form-control form-control-sm"
                    defaultValue={element.note || ""}
                    placeholder=""
                    autoComplete="off"
                    onBlur={e => handleEditNote(element, e.target.value)}
                    onKeyDown={e => {
                      if (e.key === "Enter") {
                        handleEditNote(element, (e.target as HTMLInputElement).value);
                      }
                    }}
                  />
                </div>
              )}
            </div>
            <div className="show-on-hover" onPointerDown={e => e.stopPropagation()}>
              <DropDownMenu
                showOnHover={true}
                dropdownSlot={
                  <ul className="dropdown-menu-list">
                    <li key="remove">
                      <a
                        className="dropdown-item"
                        href="#"
                        onClick={e => {
                          e.preventDefault();
                          handleRemoveObject(element);
                        }}
                      >
                        <FontAwesomeIcon icon={faTrashAlt} className="text-primary me-3" />
                        Remove
                      </a>
                    </li>
                    <li key="edit">
                      <a className="dropdown-item" href={element.edit_url}>
                        <FontAwesomeIcon icon={faPencilAlt} className="text-primary me-3" />
                        Edit {element.type}
                      </a>
                    </li>
                    <li key="note">
                      <a
                        className="dropdown-item"
                        href="#"
                        onClick={e => {
                          e.preventDefault();
                          toggleNoteEditable(element.uuid, true);
                        }}
                      >
                        <FontAwesomeIcon
                          icon={element.note ? faPencilAlt : faPlus}
                          className="text-primary me-3"
                        />
                        {element.note ? "Edit" : "New"} note
                      </a>
                    </li>
                  </ul>
                }
              />
            </div>
          </div>
        </li>
      </div>
    </div>
  );
}
