// bordercore/front-end/react/node/NodeImage.tsx
import React from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faImage, faExternalLinkAlt, faTimes } from "@fortawesome/free-solid-svg-icons";
import { Card } from "../common/Card";
import { DropDownMenu } from "../common/DropDownMenu";
import { doPost } from "../utils/reactUtils";

interface NodeImageProps {
  uuid: string;
  nodeUuid: string;
  imageTitle: string;
  imageUrl: string;
  imageDetailUrl: string;
  removeComponentUrl: string;
  onOpenImageModal: (imageUrl: string) => void;
  onEditLayout: (layout: string) => void;
}

export default function NodeImage({
  uuid,
  nodeUuid,
  imageTitle,
  imageUrl,
  imageDetailUrl,
  removeComponentUrl,
  onOpenImageModal,
  onEditLayout,
}: NodeImageProps) {
  const handleRemoveImage = () => {
    doPost(
      removeComponentUrl,
      {
        node_uuid: nodeUuid,
        uuid: uuid,
      },
      response => {
        onEditLayout(response.data.layout);
      },
      "Image removed"
    );
  };

  const handleImageClick = () => {
    onOpenImageModal(imageUrl);
  };

  const dropdownContent = (
    <ul className="dropdown-menu-list">
      <li>
        <a
          href={imageDetailUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="dropdown-menu-item"
        >
          <span className="dropdown-menu-icon">
            <FontAwesomeIcon icon={faExternalLinkAlt} className="text-primary" />
          </span>
          <span className="dropdown-menu-text">Media detail</span>
        </a>
      </li>
      <li>
        <a
          href="#"
          className="dropdown-menu-item"
          onClick={e => {
            e.preventDefault();
            handleRemoveImage();
          }}
        >
          <span className="dropdown-menu-icon">
            <FontAwesomeIcon icon={faTimes} className="text-primary" />
          </span>
          <span className="dropdown-menu-text">Remove media</span>
        </a>
      </li>
    </ul>
  );

  const titleSlot = (
    <div className="dropdown-height d-flex">
      <div className="card-title d-flex">
        <div>
          <FontAwesomeIcon icon={faImage} className="text-primary me-3" />
          {imageTitle}
        </div>
      </div>
      <div className="dropdown-menu-container ms-auto">
        <DropDownMenu dropdownSlot={dropdownContent} />
      </div>
    </div>
  );

  return (
    <div className="hover-target">
      <Card cardClassName="backdrop-filter node-color-1" titleSlot={titleSlot}>
        <img
          src={imageUrl}
          className="mw-100 cursor-pointer"
          onClick={handleImageClick}
          alt={imageTitle}
        />
      </Card>
    </div>
  );
}

// bordercore/front-end/vue/node/NodeImage.vue
<template>
    <div class="hover-target">
        <card class="backdrop-filter node-color-1">
            <template #title-slot>
                <div class="dropdown-height d-flex">
                    <div v-cloak class="card-title d-flex">
                        <div>
                            <font-awesome-icon icon="image" class="text-primary me-3" />
                            {{ imageTitle }}
                        </div>
                    </div>
                    <div class="dropdown-menu-container ms-auto">
                        <drop-down-menu :show-on-hover="true">
                            <template #dropdown>
                                <li>
                                    <a class="dropdown-item" :href="imageDetailUrl" target="_blank">
                                        <span>
                                            <font-awesome-icon icon="external-link-alt" class="text-primary me-3" />
                                        </span>
                                        Media detail
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#" @click.prevent="onRemoveImage()">
                                        <span>
                                            <font-awesome-icon icon="times" class="text-primary me-3" />
                                        </span>
                                        Remove media
                                    </a>
                                </li>
                            </template>
                        </drop-down-menu>
                    </div>
                </div>
            </template>
            <template #content>
                <img :src="imageUrl" class="mw-100" @click="onClick">
            </template>
        </card>
    </div>
</template>

<script>

    import Card from "/front-end/vue/common/Card.vue";
    import DropDownMenu from "/front-end/vue/common/DropDownMenu.vue";
    import {FontAwesomeIcon} from "@fortawesome/vue-fontawesome";

    export default {
        components: {
            Card,
            DropDownMenu,
            FontAwesomeIcon,
        },
        props: {
            uuid: {
                type: String,
                default: "",
            },
            nodeUuid: {
                type: String,
                default: "",
            },
            imageTitle: {
                type: String,
                default: "",
            },
            imageDetailUrl: {
                type: String,
                default: "",
            },
            imageUrl: {
                type: String,
                default: "",
            },
            removeComponentUrl: {
                type: String,
                default: "",
            },
        },
        setup(props, ctx) {
            function onClick() {
                ctx.emit("open-modal-note-image", props.imageUrl);
            };

            function onRemoveImage() {
                doPost(
                    props.removeComponentUrl,
                    {
                        "node_uuid": props.nodeUuid,
                        "uuid": props.uuid,
                    },
                    (response) => {
                        ctx.emit("edit-layout", response.data.layout);
                    },
                    "Image removed",
                );
            };

            return {
                onClick,
                onRemoveImage,
            };
        },
    };

</script>
