// bordercore/front-end/react/node/NodeQuote.tsx
import React, { useState, useEffect, useRef } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faQuoteLeft, faPencilAlt, faPlus } from "@fortawesome/free-solid-svg-icons";
import { Card } from "../common/Card";
import { DropDownMenu } from "../common/DropDownMenu";
import { doGet, doPost } from "../utils/reactUtils";
import type { QuoteLayoutItem, QuoteOptions, Quote } from "./types";

interface NodeQuoteProps {
  uuid: string;
  nodeUuid: string;
  quoteOptionsInitial: QuoteOptions;
  getQuoteUrl: string;
  getAndSetQuoteUrl: string;
  removeComponentUrl: string;
  editQuoteUrl: string;
  onOpenQuoteEditModal: (callback: (options: QuoteOptions) => void, data: QuoteOptions) => void;
  onEditLayout: (layout: string) => void;
}

export default function NodeQuote({
  uuid,
  nodeUuid,
  quoteOptionsInitial,
  getQuoteUrl,
  getAndSetQuoteUrl,
  removeComponentUrl,
  editQuoteUrl,
  onOpenQuoteEditModal,
  onEditLayout,
}: NodeQuoteProps) {
  const [hover, setHover] = useState(false);
  const [quote, setQuote] = useState<Quote | null>(null);
  const [quoteOptions, setQuoteOptions] = useState<QuoteOptions>(quoteOptionsInitial);
  const rotateIntervalRef = useRef<NodeJS.Timeout | null>(null);

  useEffect(() => {
    getQuote();

    if (quoteOptions.rotate !== null && quoteOptions.rotate !== -1) {
      setTimer();
    }

    return () => {
      if (rotateIntervalRef.current) {
        clearInterval(rotateIntervalRef.current);
      }
    };
  }, []);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (!hover) return;

      switch (e.key.toLowerCase()) {
        case "m":
          setQuoteOptions(prev => ({
            ...prev,
            format: prev.format === "minimal" ? "standard" : "minimal",
          }));
          break;
        case "arrowright":
          getRandomQuote();
          break;
        case "u":
          handleOpenQuoteModal();
          break;
      }
    };

    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, [hover, quoteOptions]);

  const getQuote = () => {
    doGet(
      getQuoteUrl,
      response => {
        setQuote(response.data);
      },
      "Error getting quote"
    );
  };

  const getRandomQuote = () => {
    doPost(
      getAndSetQuoteUrl,
      {
        node_uuid: nodeUuid,
        favorites_only: quoteOptions.favorites_only ? "true" : "false",
      },
      response => {
        setQuote(response.data.quote);
      }
    );
  };

  const handleQuoteRemove = () => {
    doPost(
      removeComponentUrl,
      {
        node_uuid: nodeUuid,
        uuid: uuid,
      },
      response => {
        onEditLayout(response.data.layout);
      },
      "Quote removed"
    );
  };

  const editQuote = (options: QuoteOptions) => {
    doPost(
      editQuoteUrl,
      {
        node_uuid: nodeUuid,
        uuid: uuid,
        options: JSON.stringify(options),
      },
      response => {
        setQuoteOptions(options);
        setTimer();
        onEditLayout(response.data.layout);
      }
    );
  };

  const handleOpenQuoteModal = () => {
    onOpenQuoteEditModal(editQuote, quoteOptions);
  };

  const setTimer = () => {
    if (!quoteOptions.rotate || quoteOptions.rotate === -1) {
      return;
    }

    if (rotateIntervalRef.current) {
      clearInterval(rotateIntervalRef.current);
    }

    rotateIntervalRef.current = setInterval(
      () => {
        getRandomQuote();
      },
      quoteOptions.rotate * 1000 * 60
    );
  };

  const cardClass = `backdrop-filter node-color-${quoteOptions.color}`;

  const dropdownContent = (
    <ul className="dropdown-menu-list">
      <li>
        <a
          href="#"
          className="dropdown-menu-item"
          onClick={e => {
            e.preventDefault();
            handleOpenQuoteModal();
          }}
        >
          <span className="dropdown-menu-icon">
            <FontAwesomeIcon icon={faPencilAlt} className="text-primary" />
          </span>
          <span className="dropdown-menu-text">Edit quote</span>
        </a>
      </li>
      <li>
        <a
          href="#"
          className="dropdown-menu-item"
          onClick={e => {
            e.preventDefault();
            handleQuoteRemove();
          }}
        >
          <span className="dropdown-menu-icon">
            <FontAwesomeIcon icon={faPlus} className="text-primary" />
          </span>
          <span className="dropdown-menu-text">Remove quote</span>
        </a>
      </li>
    </ul>
  );

  const titleSlot =
    quoteOptions && quoteOptions.format !== "minimal" ? (
      <>
        <div className="dropdown-height flex">
          <div className="card-title flex">
            <div>
              <FontAwesomeIcon icon={faQuoteLeft} className="text-primary me-4" />
              Quote
            </div>
          </div>
          <div className="dropdown-menu-container ms-auto">
            <DropDownMenu dropdownSlot={dropdownContent} />
          </div>
        </div>
        <hr className="divider" />
      </>
    ) : null;

  return (
    <div
      className="hover-target"
      onMouseOver={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
    >
      <Card cardClassName={cardClass} titleSlot={titleSlot}>
        {quote && (
          <div key={quote.uuid}>
            <div>{quote.quote}</div>
            <div className="text-primary text-smaller">
              <strong>{quote.source}</strong>
            </div>
          </div>
        )}
      </Card>
    </div>
  );
}

// bordercore/front-end/vue/node/NodeQuote.vue
<template>
    <div class="hover-target" @mouseover="hover = true" @mouseleave="hover = false">
        <card class="backdrop-filter" :class="cardClass" title="">
            <template #title-slot>
                <div v-if="quoteOptions && quoteOptions.format !== 'minimal'" class="dropdown-height d-flex">
                    <div v-cloak class="card-title d-flex">
                        <div>
                            <font-awesome-icon icon="quote-left" class="text-primary me-3" />
                            Quote
                        </div>
                    </div>
                    <div class="dropdown-menu-container ms-auto">
                        <drop-down-menu :show-on-hover="true">
                            <template #dropdown>
                                <li>
                                    <a class="dropdown-item" href="#" @click.prevent="handleOpenQuoteModal">
                                        <span>
                                            <font-awesome-icon icon="pencil-alt" class="text-primary me-3" />
                                        </span>
                                        Edit quote
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#" @click.prevent="handleQuoteRemove">
                                        <span>
                                            <font-awesome-icon icon="plus" class="text-primary me-3" />
                                        </span>
                                        Remove quote
                                    </a>
                                </li>
                            </template>
                        </drop-down-menu>
                    </div>
                    <hr class="divider">
                </div>
            </template>
            <template #content>
                <Transition enter-active-class="animate__animated animate__zoomIn">
                    <div v-if="quote" :key="quote.uuid">
                        <div>
                            {{ quote.quote }}
                        </div>
                        <div class="text-primary text-smaller">
                            <strong>{{ quote.source }}</strong>
                        </div>
                    </div>
                </Transition>
            </template>
        </card>
    </div>
</template>

<script>

    import Card from "/front-end/vue/common/Card.vue";
    import DropDownMenu from "/front-end/vue/common/DropDownMenu.vue";
    import {FontAwesomeIcon} from "@fortawesome/vue-fontawesome";

    export default {
        components: {
            Card,
            DropDownMenu,
            FontAwesomeIcon,
        },
        props: {
            uuid: {
                type: String,
                default: "",
            },
            nodeUuid: {
                type: String,
                default: "",
            },
            quoteOptionsInitial: {
                type: Object,
                default: function() {},
            },
            getAndSetQuoteUrl: {
                type: String,
                default: "",
            },
            getQuoteUrl: {
                type: String,
                default: "",
            },
            removeComponentUrl: {
                type: String,
                default: "",
            },
            editQuoteUrl: {
                type: String,
                default: "",
            },
        },
        emits: ["open-quote-edit-modal", "edit-layout"],
        setup(props, ctx) {
            const hover = ref(false);
            const quote = ref(null);
            const quoteOptions = ref(props.quoteOptionsInitial);
            let rotateInterval = null;

            function getQuote() {
                doGet(
                    props.getQuoteUrl,
                    (response) => {
                        quote.value = response.data;
                    },
                    "Error getting quote",
                );
            };

            function getRandomQuote() {
                doPost(
                    props.getAndSetQuoteUrl,
                    {
                        "node_uuid": props.nodeUuid,
                        "favorites_only": quoteOptions.value.favorites_only,
                    },
                    (response) => {
                        quote.value = response.data.quote;
                    },
                );
            };

            function handleQuoteRemove() {
                doPost(
                    props.removeComponentUrl,
                    {
                        "node_uuid": props.nodeUuid,
                        "uuid": props.uuid,
                    },
                    (response) => {
                        ctx.emit("edit-layout", response.data.layout);
                    },
                    "Quote removed",
                );
            };

            function editQuote(options) {
                doPost(
                    props.editQuoteUrl,
                    {
                        "node_uuid": props.nodeUuid,
                        "uuid": props.uuid,
                        "options": JSON.stringify(options),
                    },
                    (response) => {
                        quoteOptions.value = options;
                        setTimer();
                        ctx.emit("edit-layout", response.data.layout);
                    },
                );
            };

            function handleOpenQuoteModal() {
                ctx.emit("open-quote-edit-modal", editQuote, quoteOptions.value);
            };

            function setTimer() {
                if (!quoteOptions.value.rotate || quoteOptions.rotate === -1) {
                    return;
                }
                clearInterval(rotateInterval);
                rotateInterval = setInterval( () => {
                    getRandomQuote();
                }, quoteOptions.value.rotate * 1000 * 60);
            };

            onMounted(() => {
                getQuote();

                if (quoteOptions.value.rotate !== null && quoteOptions.value.rotate !== -1) {
                    setTimer();
                }

                hotkeys("m,right,u", function(event, handler) {
                    if (!hover.value) {
                        return;
                    }
                    switch (handler.key) {
                    case "m":
                        quoteOptions.value.format = quoteOptions.value.format === "minimal" ? "standard": "minimal";
                        break;
                    case "right":
                        getRandomQuote();
                        break;
                    case "u":
                        handleOpenQuoteModal();
                        break;
                    }
                });
            });

            onUnmounted(() => {
                clearInterval(rotateInterval);
            });

            const cardClass = computed(() => {
                return `node-color-${quoteOptions.value.color}`;
            });

            return {
                cardClass,
                handleOpenQuoteModal,
                handleQuoteRemove,
                hover,
                quote,
                quoteOptions,
            };
        },
    };

</script>
