// bordercore/front-end/react/fitness/WorkoutGraph.tsx
import React, { useRef, useEffect, useState, useMemo } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faChevronLeft, faChevronRight } from "@fortawesome/free-solid-svg-icons";
import Chart from "chart.js/auto";
import Rainbow from "rainbowvis.js";
import { Card } from "../common/Card";
import { doGet } from "../utils/reactUtils";
import type { PlotInfo, PlotType } from "./types";

interface WorkoutGraphProps {
  getWorkoutDataUrl: string;
}

function capitalizeFirstLetter(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

export function WorkoutGraph({ getWorkoutDataUrl }: WorkoutGraphProps) {
  const chartRef = useRef<HTMLCanvasElement>(null);
  const chartInstanceRef = useRef<Chart | null>(null);
  const [plotInfo, setPlotInfo] = useState<PlotInfo | null>(null);
  const [currentPlotType, setCurrentPlotType] = useState<PlotType>("reps");

  const hasNote = useMemo(() => {
    return plotInfo?.notes?.some((note) => note !== null) ?? false;
  }, [plotInfo]);

  const hasWeight = useMemo(() => {
    return plotInfo?.plot_data && "weight" in plotInfo.plot_data;
  }, [plotInfo]);

  const hasDuration = useMemo(() => {
    return plotInfo?.plot_data && "duration" in plotInfo.plot_data;
  }, [plotInfo]);

  function firstSet(workoutData: number[]): number {
    return workoutData[0];
  }

  function getGradient(numberOfItems: number): string[] | undefined {
    const styles = getComputedStyle(document.body);

    if (numberOfItems <= 1) {
      return undefined;
    }

    const rainbow = new Rainbow();
    rainbow.setNumberRange(1, numberOfItems);
    rainbow.setSpectrum(
      styles.getPropertyValue("--chart-gradient-start").trim(),
      styles.getPropertyValue("--chart-gradient-end").trim()
    );

    const colorArray: string[] = [];
    for (let i = 1; i <= numberOfItems; i++) {
      const hexColour = rainbow.colourAt(i);
      colorArray.push(`#${hexColour}`);
    }
    return colorArray;
  }

  function createChart(data: PlotInfo) {
    if (!chartRef.current) return;

    const scaleYText = capitalizeFirstLetter(currentPlotType);
    const styles = getComputedStyle(document.body);
    const ctx = chartRef.current.getContext("2d");
    if (!ctx) return;

    const gradient = getGradient(data.plot_data[currentPlotType]?.length || 0);

    chartInstanceRef.current = new Chart(ctx, {
      type: "bar",
      data: {
        labels: data.labels,
        datasets: [
          {
            data: data.plot_data[currentPlotType]?.map(firstSet) || [],
            barThickness: 40,
            backgroundColor: gradient,
          },
        ],
      },
      options: {
        elements: {
          bar: {
            borderRadius: 10,
          },
        },
        animation: {
          onProgress: function (chartInstance) {
            const ctx = this.ctx;
            ctx.textAlign = "center";
            ctx.textBaseline = "bottom";
            ctx.fillStyle = styles.getPropertyValue("--chart-fill-color");
            ctx.font = "bold 18px Arial";

            this.data.datasets.forEach(function (dataset, i) {
              const meta = chartInstance.chart.getDatasetMeta(i);
              meta.data.forEach(function (bar, index) {
                const value = dataset.data[index] as number;
                const note = data.notes[index];
                ctx.fillText(value + (note ? "\n*" : ""), bar.x, bar.y + 30);
              });
            });
          },
        },
        plugins: {
          title: { display: false },
          legend: { display: false },
          tooltip: {
            callbacks: {
              label() {
                return null as unknown as string;
              },
              title(tooltipItem) {
                const dataIndex = tooltipItem[0].dataIndex;
                const plotData = data.plot_data[currentPlotType]?.[dataIndex];
                const note = data.notes[dataIndex];
                return `${capitalizeFirstLetter(currentPlotType)}: ${plotData}${note ? `\nNote: ${note}` : ""}`;
              },
            },
            titleMarginBottom: 0,
            titleFont: { size: 18 },
          },
        },
        scales: {
          x: {
            grid: { color: "#21295c" },
            ticks: {
              color: styles.getPropertyValue("--chart-tick-color"),
              font: { family: "Poppins", size: 16 },
            },
          },
          y: {
            grid: { color: "#21295c" },
            title: {
              display: true,
              text: scaleYText,
              color: styles.getPropertyValue("--chart-title-color"),
              font: { family: "Poppins", size: 24 },
            },
            ticks: {
              color: styles.getPropertyValue("--chart-tick-color"),
              font: { family: "Poppins", size: 16 },
            },
          },
        },
        font: { size: 14 },
      },
    });
  }

  function updateChart() {
    if (!chartInstanceRef.current || !plotInfo) return;

    chartInstanceRef.current.data.labels = plotInfo.labels;
    chartInstanceRef.current.data.datasets[0].data =
      plotInfo.plot_data[currentPlotType]?.map(firstSet) || [];
    const styles = getComputedStyle(document.body);
    chartInstanceRef.current.options.scales = {
      ...chartInstanceRef.current.options.scales,
      y: {
        ...chartInstanceRef.current.options.scales?.y,
        title: {
          display: true,
          text: capitalizeFirstLetter(currentPlotType),
          color: styles.getPropertyValue("--chart-title-color"),
          font: { family: "Poppins", size: 24 },
        },
      },
    };
    chartInstanceRef.current.update();
  }

  function paginate(direction: "prev" | "next") {
    const pageNumber =
      plotInfo?.paginator?.[direction === "prev" ? "previous_page_number" : "next_page_number"] ?? 1;

    doGet(
      getWorkoutDataUrl + pageNumber,
      (response) => {
        const wd = response.data.workout_data;
        const newPlotInfo: PlotInfo = {
          labels: wd.labels,
          plot_data: wd.plot_data,
          paginator: wd.paginator,
          notes: wd.notes ?? [],
        };
        setPlotInfo(newPlotInfo);

        if (!chartInstanceRef.current) {
          createChart(newPlotInfo);
        } else {
          chartInstanceRef.current.data.labels = wd.labels;
          chartInstanceRef.current.data.datasets[0].data =
            wd.plot_data[currentPlotType]?.map(firstSet) || [];
          chartInstanceRef.current.update();
        }
      },
      "Error getting workout data"
    );
  }

  function switchPlot(dataset: PlotType) {
    setCurrentPlotType(dataset);
  }

  useEffect(() => {
    paginate("next");
    return () => {
      chartInstanceRef.current?.destroy();
    };
  }, []);

  useEffect(() => {
    if (plotInfo && chartInstanceRef.current) {
      updateChart();
    }
  }, [currentPlotType]);

  return (
    <Card cardClassName="flex-grow-0 me-2 pt-3 mb-gutter backdrop-filter" title="">
      <div className="d-flex">
        <div className="d-flex w-100">
          <div className="btn-group" role="group" aria-label="Plot type selection">
            <button
              type="button"
              className={`btn btn-primary ${currentPlotType === "reps" ? "active" : ""}`}
              onClick={() => switchPlot("reps")}
            >
              Reps
            </button>
            {hasWeight && (
              <button
                type="button"
                className={`btn btn-primary ${currentPlotType === "weight" ? "active" : ""}`}
                onClick={() => switchPlot("weight")}
              >
                Weight
              </button>
            )}
            {hasDuration && (
              <button
                type="button"
                className={`btn btn-primary ${currentPlotType === "duration" ? "active" : ""}`}
                onClick={() => switchPlot("duration")}
              >
                Duration
              </button>
            )}
          </div>
          <div className="d-flex justify-content-center w-100">
            <h2 className="fw-semibold">Workout Data</h2>
          </div>
        </div>
        <h5 className="text-nowrap ms-auto">
          {plotInfo?.paginator?.has_previous ? (
            <a href="#" onClick={(e) => { e.preventDefault(); paginate("prev"); }}>
              <FontAwesomeIcon icon={faChevronLeft} className="text-emphasis glow icon-hover" />
            </a>
          ) : (
            <FontAwesomeIcon icon={faChevronLeft} className="text-emphasis icon-disabled" />
          )}
          {plotInfo?.paginator?.has_next ? (
            <a href="#" className="ms-1" onClick={(e) => { e.preventDefault(); paginate("next"); }}>
              <FontAwesomeIcon icon={faChevronRight} className="text-emphasis glow icon-hover" />
            </a>
          ) : (
            <FontAwesomeIcon icon={faChevronRight} className="text-emphasis icon-disabled" />
          )}
        </h5>
      </div>
      <canvas ref={chartRef} id="exercise-detail-chart" className="w-100" />
      {hasNote && <div id="fitness-has-note">* workout note</div>}
    </Card>
  );
}

export default WorkoutGraph;

// bordercore/front-end/vue/fitness/WorkoutGraph.vue
<template>
    <card title="" class="flex-grow-0 me-2 pt-3 backdrop-filter">
        <template #content>
            <div class="d-flex">
                <div class="d-flex w-100">
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <button type="button" class="btn btn-primary" :class="{'active': currentPlotType === 'reps' }" @click="switchPlot('reps')">
                            Reps
                        </button>
                        <button v-if="plotInfo?.plot_data && 'weight' in plotInfo.plot_data" type="button" class="btn btn-primary" :class="{'active': currentPlotType === 'weight' }" @click="switchPlot('weight')">
                            Weight
                        </button>
                        <button v-if="plotInfo?.plot_data && 'duration' in plotInfo.plot_data" type="button" class="btn btn-primary" :class="{'active': currentPlotType === 'duration' }" @click="switchPlot('duration')">
                            Duration
                        </button>
                    </div>
                    <div class="d-flex justify-content-center w-100">
                        <h2 class="fw-semibold">
                            Workout Data
                        </h2>
                    </div>
                </div>
                <h5 class="text-nowrap ms-auto">
                    <a v-if="plotInfo && plotInfo.paginator.has_previous" href="#" @click.prevent="paginate('prev')">
                        <font-awesome-icon icon="chevron-left" class="text-emphasis glow icon-hover" />
                    </a>
                    <span v-else>
                        <font-awesome-icon icon="chevron-left" class="text-emphasis icon-disabled" />
                    </span>
                    <a v-if="plotInfo && plotInfo.paginator.has_next" href="#" class="ms-1" @click.prevent="paginate('next')">
                        <font-awesome-icon icon="chevron-right" class="text-emphasis glow icon-hover" />
                    </a>
                    <span v-else>
                        <font-awesome-icon icon="chevron-right" class="text-emphasis icon-disabled" />
                    </span>
                </h5>
            </div>
            <canvas id="exercise-detail-chart" class="w-100" />
            <div v-if="hasNote" id="fitness-has-note">
                * workout note
            </div>
        </template>
    </card>
</template>

<script>

    import {capitalizeFirstLetter} from "/front-end/util.js";
    import Card from "/front-end/vue/common/Card.vue";
    import {FontAwesomeIcon} from "@fortawesome/vue-fontawesome";

    export default {
        components: {
            Card,
            FontAwesomeIcon,
        },
        props: {
            date: {
                default: "",
                type: String,
            },
            getWorkoutDataUrl: {
                default: "",
                type: String,
            },
        },
        setup(props) {
            const currentPlotType = ref("reps");
            let myChart = null;
            const plotInfo = ref(null);
            const hasNote = computed(() => {
                return plotInfo.value && plotInfo.value.notes.filter((x) => x !== null).length > 0;
            });

            function firstSet(workoutData) {
                return workoutData[0];
            }

            function getGradient(numberOfItems) {
                const styles = getComputedStyle(document.body);

                if (numberOfItems <= 1) {
                    return;
                }

                // The Rainbow object is from the RainbowVis-JS package
                const rainbow = new Rainbow();
                rainbow.setNumberRange(1, numberOfItems);
                // Use trim() to remove the whitespace preceding the CSS property value
                rainbow.setSpectrum(styles.getPropertyValue("--chart-gradient-start").trim(), styles.getPropertyValue("--chart-gradient-end").trim());

                const colorArray = [];
                for (let i = 1; i <= numberOfItems; i++) {
                    const hexColour = rainbow.colourAt(i);
                    colorArray.push(`#${hexColour}`);
                }
                return colorArray;
            };

            function paginate(direction) {
                const pageNumber =
                    plotInfo.value?.paginator?.[direction === "prev" ? "previous_page_number" : "next_page_number"] ?? 1;

                doGet(
                    props.getWorkoutDataUrl + pageNumber,
                    (response) => {
                        const wd = response.data.workout_data;
                        plotInfo.value = {
                            labels: wd.labels,
                            plot_data: wd.plot_data,
                            paginator: wd.paginator,
                            notes: wd.notes ?? [],
                        };

                        if (!myChart) {
                            createChart();
                            return;
                        }

                        myChart.data.labels = response.data.workout_data.labels;
                        myChart.data.datasets[0].data = response.data.workout_data.plot_data[currentPlotType.value].map(firstSet);
                        myChart.update();
                        plotInfo.value.paginator = response.data.workout_data.paginator;
                    },
                    "Error getting workout data",
                );
            };

            function switchPlot(dataset) {
                currentPlotType.value = dataset;
                myChart.data.datasets[0].data = plotInfo.value.plot_data[dataset].map(firstSet);
                myChart.options.scales.y.title.text = capitalizeFirstLetter(dataset);
                myChart.update();
            };

            function createChart() {
                const scaleYText = capitalizeFirstLetter(currentPlotType.value);
                const styles = getComputedStyle(document.body);
                const ctx = document.getElementById("exercise-detail-chart").getContext("2d");

                myChart = new Chart(ctx, {
                    type: "bar",
                    data: {
                        labels: plotInfo.value.labels,
                        datasets: [
                            {
                                data: plotInfo.value.plot_data[currentPlotType.value].map(firstSet),
                                barThickness: 40,
                                backgroundColor: function(context) {
                                    const chart = context.chart;
                                    const {ctx, chartArea} = chart;

                                    if (!chartArea) {
                                        // This case happens on initial chart load
                                        return;
                                    }
                                    return getGradient(plotInfo.value.plot_data[currentPlotType.value].length);
                                },
                            },
                        ],
                    },
                    options: {
                        borderRadius: 10,
                        animation: {
                            onProgress: function(chartInstance) {
                                const ctx = this.ctx;
                                ctx.textAlign = "center";
                                ctx.textBaseline = "bottom";
                                ctx.fillStyle = styles.getPropertyValue("--chart-fill-color");
                                ctx.font="bold 18px Arial";

                                this.data.datasets.forEach(function(dataset, i) {
                                    const meta = chartInstance.chart.getDatasetMeta(i);
                                    meta.data.forEach(function(bar, index) {
                                        const data = dataset.data[index];
                                        const note = plotInfo.value.notes[index];
                                        ctx.fillText(data + (note ? "\n*" : ""), bar.x, bar.y + 30);
                                    });
                                });
                            },
                        },
                        plugins: {
                            title: {
                                display: false,
                            },
                            legend: {
                                display: false,
                            },
                            tooltip: {
                                callbacks: {
                                    label(tooltipItem) {
                                        return null;
                                    },
                                    title(tooltipItem) {
                                        const data = plotInfo.value.plot_data[currentPlotType.value][tooltipItem[0].dataIndex];
                                        const note = plotInfo.value.notes[tooltipItem[0].dataIndex];
                                        return `${capitalizeFirstLetter(currentPlotType.value)}: ${data}` + (note ? `\nNote: ${note}` : "");
                                    },
                                },
                                titleMarginBottom: 0,
                                titleFont: {
                                    size: 18,
                                },
                            },
                        },
                        scales: {
                            x: {
                                grid: {
                                    color: "#21295c",
                                },
                                ticks: {
                                    color: styles.getPropertyValue("--chart-tick-color"),
                                    font: {
                                        family: "Poppins",
                                        size: 16,
                                    },
                                },
                            },
                            y: {
                                grid: {
                                    color: "#21295c",
                                },
                                title: {
                                    display: true,
                                    text: scaleYText,
                                    color: styles.getPropertyValue("--chart-title-color"),
                                    font: {
                                        family: "Poppins",
                                        size: 24,
                                    },
                                },
                                ticks: {
                                    color: styles.getPropertyValue("--chart-tick-color"),
                                    font: {
                                        family: "Poppins",
                                        size: 16,
                                    },
                                },
                            },
                        },
                        font: {
                            size: 14,
                        },
                    },
                });
            };

            onMounted(() => {
                paginate("next");
            });

            return {
                currentPlotType,
                hasNote,
                paginate,
                plotInfo,
                switchPlot,
            };
        },
    };

</script>
