// bordercore/front-end/vue/node/NodeTodoList.vue
<template>
    <div class="hover-reveal-target">
        <card title="" class="backdrop-filter node-color-1 position-relative">
            <template #title-slot>
                <div class="card-title d-flex">
                    <div>
                        <font-awesome-icon icon="tasks" class="text-primary me-3" />
                        Todo Tasks
                    </div>
                    <div class="dropdown-menu-container ms-auto">
                        <drop-down-menu class="d-none hover-reveal-object" :show-on-hover="false">
                            <template #dropdown>
                                <li>
                                    <a class="dropdown-item" href="#" @click.prevent="handleTodoCreate">
                                        <span>
                                            <font-awesome-icon icon="plus" class="text-primary me-3" />
                                        </span>
                                        Add Task
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#" @click.prevent="onDeleteTodoList">
                                        <span>
                                            <font-awesome-icon icon="plus" class="text-primary me-3" />
                                        </span>
                                        Remove Todo List
                                    </a>
                                </li>
                            </template>
                        </drop-down-menu>
                    </div>
                </div>
            </template>

            <template #content>
                <hr class="divider">
                <ul id="sort-container-tags" class="list-group list-group-flush interior-borders">
                    <slick-list
                        v-model:list="todoList"
                        :distance="3"
                        helper-class="slicklist-helper"
                        @sort-end="handleSort"
                    >
                        <slick-item
                            v-for="(element, index) in todoList"
                            :key="element.uuid"
                            :index="index"
                            class="slicklist-item"
                        >
                            <div class="slicklist-list-item-inner">
                                <li v-cloak :key="element.uuid" class="hover-target list-group-item pe-0" :data-uuid="element.uuid">
                                    <div class="dropdown-height d-flex align-items-start">
                                        <div>
                                            {{ element.name }}
                                            <div v-if="element.url" class="node-url">
                                                <a :href="element.url">Link</a>
                                            </div>
                                            <div v-if="element.note" class="node-object-note">
                                                {{ element.note }}
                                            </div>
                                        </div>

                                        <drop-down-menu :show-on-hover="true">
                                            <template #dropdown>
                                                <li>
                                                    <a class="dropdown-item" href="#" @click.prevent="handleTodoEdit(element)">
                                                        <font-awesome-icon icon="pencil-alt" class="text-primary me-3" />Edit
                                                    </a>
                                                </li>
                                                <li>
                                                    <a class="dropdown-item" href="#" @click.prevent="handleTodoRemove(element.uuid)">
                                                        <font-awesome-icon icon="trash-alt" class="text-primary me-3" />Remove
                                                    </a>
                                                </li>
                                            </template>
                                        </drop-down-menu>
                                    </div>
                                </li>
                            </div>
                        </slick-item>
                    </slick-list>
                    <div v-if="todoList.length == 0" v-cloak :key="1" class="text-muted">
                        No tasks
                    </div>
                </ul>
            </template>
        </card>
    </div>
</template>

<script>

    import Card from "/front-end/vue/common/Card.vue";
    import DropDownMenu from "/front-end/vue/common/DropDownMenu.vue";
    import {FontAwesomeIcon} from "@fortawesome/vue-fontawesome";
    import {SlickList, SlickItem} from "vue-slicksort";

    export default {
        components: {
            Card,
            DropDownMenu,
            FontAwesomeIcon,
            SlickItem,
            SlickList,
        },
        props: {
            nodeUuid: {
                type: String,
                default: "",
            },
            getTodoListUrl: {
                type: String,
                default: "",
            },
            addNodeTodoUrl: {
                type: String,
                default: "",
            },
            removeNodeTodoUrl: {
                type: String,
                default: "",
            },
            sortNodeTodosUrl: {
                type: String,
                default: "",
            },
            deleteTodoListUrl: {
                type: String,
                default: "",
            },
        },
        emits: ["open-create-edit-todo-modal", "edit-layout"],
        setup(props, ctx) {
            const todoList = ref([]);

            function addNodeTodo(todoUuid) {
                doPost(
                    props.addNodeTodoUrl,
                    {
                        "node_uuid": props.nodeUuid,
                        "todo_uuid": todoUuid,
                    },
                    () => {
                        getTodoList();
                    },
                );
            };

            function getTodoList() {
                doGet(
                    props.getTodoListUrl,
                    (response) => {
                        todoList.value = response.data.todo_list;
                    },
                    "Error getting todo list",
                );
            };

            function handleTodoCreate() {
                ctx.emit("open-todo-editor-modal", "Create");
            };

            function handleTodoEdit(todoInfo) {
                ctx.emit("open-todo-editor-modal", "Edit", todoInfo);
            };

            function onDeleteTodoList() {
                doPost(
                    props.deleteTodoListUrl,
                    {
                        "node_uuid": props.nodeUuid,
                    },
                    (response) => {
                        ctx.emit("edit-layout", response.data.layout);
                    },
                    "Todo list deleted",
                );
            };

            function handleTodoRemove(todoUuid) {
                // Delete the todo item, and the NodeTodo object
                //  will automatically be deleted as well
                axios.delete(props.removeNodeTodoUrl.replace("00000000-0000-0000-0000-000000000000", todoUuid))
                    .then((response) => {
                        EventBus.$emit(
                            "toast",
                            {
                                "body": "Todo task deleted",
                                "variant": "info",
                            },
                        );
                        getTodoList();
                    }, (error) => {
                        console.log(error);
                    });
            };

            function handleSort(event) {
                if (event.oldIndex === event.newIndex) {
                    return;
                }
                const todoUuid = todoList.value[event.oldIndex].uuid;

                // The backend expects the ordering to begin
                // with 1, not 0, so add 1.
                const newPosition = event.newIndex + 1;

                doPost(
                    props.sortNodeTodosUrl,
                    {
                        "node_uuid": props.nodeUuid,
                        "todo_uuid": todoUuid,
                        "new_position": newPosition,
                    },
                    () => {},
                );
            };

            onMounted(() => {
                getTodoList();
            });

            return {
                addNodeTodo,
                getTodoList,
                handleSort,
                handleTodoCreate,
                handleTodoRemove,
                onDeleteTodoList,
                handleTodoEdit,
                todoList,
            };
        },
    };

</script>

// bordercore/front-end/react/node/NodeTodoList.tsx
import React, {
  useState,
  useEffect,
  forwardRef,
  useImperativeHandle,
  useRef,
  useLayoutEffect,
} from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faTasks,
  faPlus,
  faPencilAlt,
  faTrashAlt,
  faBars,
} from "@fortawesome/free-solid-svg-icons";
import {
  DndContext,
  closestCenter,
  KeyboardSensor,
  PointerSensor,
  useSensor,
  useSensors,
  DragEndEvent,
} from "@dnd-kit/core";
import {
  arrayMove,
  SortableContext,
  sortableKeyboardCoordinates,
  useSortable,
  verticalListSortingStrategy,
} from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { Card } from "../common/Card";
import { DropDownMenu } from "../common/DropDownMenu";
import { doGet, doPost, doDelete } from "../utils/reactUtils";
import type { NodeTodoItem } from "./types";

interface SortableTodoItemProps {
  element: NodeTodoItem;
  onEdit: (todoInfo: NodeTodoItem) => void;
  onRemove: (uuid: string) => void;
}

function SortableTodoItem({ element, onEdit, onRemove }: SortableTodoItemProps) {
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({
    id: element.uuid,
  });

  const nodeRef = useRef<HTMLDivElement | null>(null);
  const setRef = (el: HTMLDivElement | null) => {
    setNodeRef(el);
    nodeRef.current = el;
  };

  useLayoutEffect(() => {
    const el = nodeRef.current;
    if (!el) return;
    el.style.transform = CSS.Transform.toString(transform);
    el.style.transition = transition;
  }, [transform, transition]);

  return (
    <div ref={setRef} className={`slicklist-item ${isDragging ? "dragging" : ""}`}>
      <div className="slicklist-list-item-inner">
        <li className="hover-target list-group-item pe-0" data-uuid={element.uuid}>
          <div className="dropdown-height d-flex align-items-start">
            <div className="drag-handle pe-2 cursor-grab" {...attributes} {...listeners}>
              <FontAwesomeIcon icon={faBars} />
            </div>
            <div>
              {element.name}
              {element.url && (
                <div className="node-url">
                  <a href={element.url}>Link</a>
                </div>
              )}
              {element.note && <div className="node-object-note">{element.note}</div>}
            </div>

            <div className="ms-auto">
              <DropDownMenu
                dropdownSlot={
                  <ul className="dropdown-menu-list">
                    <li>
                      <a
                        href="#"
                        className="dropdown-menu-item"
                        onClick={e => {
                          e.preventDefault();
                          onEdit(element);
                        }}
                      >
                        <span className="dropdown-menu-icon">
                          <FontAwesomeIcon icon={faPencilAlt} className="text-primary" />
                        </span>
                        <span className="dropdown-menu-text">Edit</span>
                      </a>
                    </li>
                    <li>
                      <a
                        href="#"
                        className="dropdown-menu-item"
                        onClick={e => {
                          e.preventDefault();
                          onRemove(element.uuid);
                        }}
                      >
                        <span className="dropdown-menu-icon">
                          <FontAwesomeIcon icon={faTrashAlt} className="text-primary" />
                        </span>
                        <span className="dropdown-menu-text">Remove</span>
                      </a>
                    </li>
                  </ul>
                }
              />
            </div>
          </div>
        </li>
      </div>
    </div>
  );
}

interface NodeTodoListProps {
  nodeUuid: string;
  getTodoListUrl: string;
  addNodeTodoUrl: string;
  removeNodeTodoUrl: string;
  sortNodeTodosUrl: string;
  deleteTodoListUrl: string;
  onOpenTodoEditorModal: (action: "Create" | "Edit", todoInfo?: NodeTodoItem) => void;
  onEditLayout: (layout: string) => void;
}

export interface NodeTodoListHandle {
  getTodoList: () => void;
  addNodeTodo: (todoUuid: string) => void;
}

const NodeTodoList = forwardRef<NodeTodoListHandle, NodeTodoListProps>(function NodeTodoList(
  {
    nodeUuid,
    getTodoListUrl,
    addNodeTodoUrl,
    removeNodeTodoUrl,
    sortNodeTodosUrl,
    deleteTodoListUrl,
    onOpenTodoEditorModal,
    onEditLayout,
  },
  ref
) {
  const [todoList, setTodoList] = useState<NodeTodoItem[]>([]);

  const sensors = useSensors(
    useSensor(PointerSensor, {
      activationConstraint: {
        distance: 5,
      },
    }),
    useSensor(KeyboardSensor, {
      coordinateGetter: sortableKeyboardCoordinates,
    })
  );

  useEffect(() => {
    getTodoList();
  }, []);

  useImperativeHandle(ref, () => ({
    getTodoList,
    addNodeTodo,
  }));

  const getTodoList = () => {
    doGet(
      getTodoListUrl,
      response => {
        setTodoList(response.data.todo_list);
      },
      "Error getting todo list"
    );
  };

  const addNodeTodo = (todoUuid: string) => {
    doPost(
      addNodeTodoUrl,
      {
        node_uuid: nodeUuid,
        todo_uuid: todoUuid,
      },
      () => {
        getTodoList();
      }
    );
  };

  const handleTodoCreate = () => {
    onOpenTodoEditorModal("Create");
  };

  const handleTodoEdit = (todoInfo: NodeTodoItem) => {
    onOpenTodoEditorModal("Edit", todoInfo);
  };

  const handleTodoRemove = (todoUuid: string) => {
    const url = removeNodeTodoUrl.replace("00000000-0000-0000-0000-000000000000", todoUuid);
    doDelete(
      url,
      () => {
        getTodoList();
      },
      "Todo task deleted"
    );
  };

  const handleDeleteTodoList = () => {
    doPost(
      deleteTodoListUrl,
      {
        node_uuid: nodeUuid,
      },
      response => {
        onEditLayout(response.data.layout);
      },
      "Todo list deleted"
    );
  };

  const handleDragEnd = (event: DragEndEvent) => {
    const { active, over } = event;

    if (over && active.id !== over.id) {
      const oldIndex = todoList.findIndex(item => item.uuid === active.id);
      const newIndex = todoList.findIndex(item => item.uuid === over.id);

      const newList = arrayMove(todoList, oldIndex, newIndex);
      setTodoList(newList);

      // Backend expects 1-indexed position
      const newPosition = newIndex + 1;
      doPost(
        sortNodeTodosUrl,
        {
          node_uuid: nodeUuid,
          todo_uuid: active.id.toString(),
          new_position: newPosition.toString(),
        },
        () => {}
      );
    }
  };

  const headerDropdownContent = (
    <ul className="dropdown-menu-list">
      <li>
        <a
          href="#"
          className="dropdown-menu-item"
          onClick={e => {
            e.preventDefault();
            handleTodoCreate();
          }}
        >
          <span className="dropdown-menu-icon">
            <FontAwesomeIcon icon={faPlus} className="text-primary" />
          </span>
          <span className="dropdown-menu-text">Add Task</span>
        </a>
      </li>
      <li>
        <a
          href="#"
          className="dropdown-menu-item"
          onClick={e => {
            e.preventDefault();
            handleDeleteTodoList();
          }}
        >
          <span className="dropdown-menu-icon">
            <FontAwesomeIcon icon={faPlus} className="text-primary" />
          </span>
          <span className="dropdown-menu-text">Remove Todo List</span>
        </a>
      </li>
    </ul>
  );

  const titleSlot = (
    <div className="card-title d-flex">
      <div>
        <FontAwesomeIcon icon={faTasks} className="text-primary me-3" />
        Todo Tasks
      </div>
      <div className="dropdown-menu-container ms-auto hover-reveal-content">
        <DropDownMenu dropdownSlot={headerDropdownContent} />
      </div>
    </div>
  );

  return (
    <div className="hover-reveal-target">
      <Card cardClassName="backdrop-filter node-color-1 position-relative" titleSlot={titleSlot}>
        <hr className="divider" />
        <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={handleDragEnd}>
          <SortableContext
            items={todoList.map(item => item.uuid)}
            strategy={verticalListSortingStrategy}
          >
            <ul id="sort-container-tags" className="list-group list-group-flush interior-borders">
              {todoList.map(element => (
                <SortableTodoItem
                  key={element.uuid}
                  element={element}
                  onEdit={handleTodoEdit}
                  onRemove={handleTodoRemove}
                />
              ))}
              {todoList.length === 0 && <div className="text-muted">No tasks</div>}
            </ul>
          </SortableContext>
        </DndContext>
      </Card>
    </div>
  );
});

export default NodeTodoList;
