// bordercore/front-end/vue/node/NodeNote.vue
<template>
    <div class="hover-target">
        <card class="backdrop-filter" :class="cardClass">
            <template #title-slot>
                <div v-cloak class="card-title d-flex">
                    <div class="dropdown-height d-flex">
                        <div>
                            <font-awesome-icon icon="sticky-note" class="text-primary me-3" />
                        </div>
                        <div class="w-100">
                            <input v-if="isEditingName" v-model="nodeNote.name" class="form-control w-100" @blur="handleNameEdit" @keydown.enter="handleNameEdit">
                            <span v-else-if="note" @dblclick="handleNameEdit">
                                {{ nodeNote.name }}
                            </span>
                        </div>
                    </div>
                    <div v-if="note !== ''" class="dropdown-menu-container ms-auto">
                        <drop-down-menu :show-on-hover="true">
                            <template #dropdown>
                                <li>
                                    <a class="dropdown-item" href="#" @click.prevent="handleNoteEdit()">
                                        <span>
                                            <font-awesome-icon icon="pencil-alt" class="text-primary me-3" />
                                        </span>
                                        Edit note
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#" @click.prevent="onOpenNoteMetadataModal()">
                                        <span>
                                            <font-awesome-icon icon="pencil-alt" class="text-primary me-3" />
                                        </span>
                                        Edit note metadata
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#" @click.prevent="handleNoteDelete()">
                                        <span>
                                            <font-awesome-icon icon="times" class="text-primary me-3" />
                                        </span>
                                        Delete note
                                    </a>
                                </li>
                            </template>
                        </drop-down-menu>
                    </div>
                </div>
            </template>
            <template #content>
                <hr class="divider">
                <editable-text-area
                    ref="editableTextArea"
                    v-model="noteContents"
                    default-value="No content"
                    class="node-note"
                    :hide-add-button="true"
                />
            </template>
        </card>
    </div>
</template>

<script>

    import Card from "/front-end/vue/common/Card.vue";
    import DropDownMenu from "/front-end/vue/common/DropDownMenu.vue";
    import EditableTextArea from "/front-end/vue/common/EditableTextArea.vue";
    import {FontAwesomeIcon} from "@fortawesome/vue-fontawesome";

    export default {
        components: {
            Card,
            DropDownMenu,
            EditableTextArea,
            FontAwesomeIcon,
        },
        props: {
            nodeUuid: {
                type: String,
                default: "",
            },
            nodeNoteInitial: {
                type: Object,
                default: function() {},
            },
            deleteNoteUrl: {
                type: String,
                default: "",
            },
            noteUrl: {
                type: String,
                default: "",
            },
            setNoteColorUrl: {
                type: String,
                default: "",
            },
        },
        emits: ["delete-note", "open-note-metadata-modal", "edit-layout"],
        setup(props, ctx) {
            const colors = [1, 2, 3, 4];
            let nameCache = null;
            const action = ref("Edit");
            const isEditingName = ref(false);
            const nodeNote = ref({});
            const note = ref("");
            const noteContents = ref("");

            const editableTextArea = ref(null);

            watch(noteContents, (newValue) => {
                if (newValue) {
                    editNoteContents();
                }
            });

            function getClass(color) {
                const selectedColor = color === (nodeNote.value && nodeNote.value.color) ? "selected-color" : "";
                return `node-color-${color} ${selectedColor}`;
            };

            function handleNoteEdit() {
                editableTextArea.value.editNote(!note.value.content);
            };

            function handleNameEdit() {
                nameCache = note.value.name;
                isEditingName.value = true;
            };

            function onOpenNoteMetadataModal(actionValue) {
                ctx.emit("open-note-metadata-modal", editNoteMetadata, nodeNote.value);
            };

            function handleNameEdit() {
                isEditingName.value = false;
                // If the name hasn't changed, abort
                if (nameCache === nodeNote.value.name) {
                    return;
                }
                editNoteMetadata(nodeNote.value);
            };

            function handleNoteDelete() {
                doPost(
                    props.deleteNoteUrl,
                    {
                        "node_uuid": props.nodeUuid,
                        "note_uuid": note.value.uuid,
                    },
                    (response) => {
                        ctx.emit("edit-layout", response.data.layout);
                    },
                    "Note deleted",
                );

                ctx.emit("delete-note", note.value.uuid);
            };

            function editNoteMetadata(note) {
                doPost(
                    props.setNoteColorUrl,
                    {
                        "node_uuid": props.nodeUuid,
                        "note_uuid": note.uuid,
                        "color": note.color,
                    },
                    (response) => {
                        nodeNote.value.color = note.color;
                    },
                    "",
                    "",
                );
                editNoteContents();
            };

            function editNoteContents() {
                doPut(
                    props.noteUrl,
                    {
                        "uuid": nodeNote.value.uuid,
                        "name": nodeNote.value.name,
                        "content": noteContents.value,
                        "is_note": true,
                    },
                    (response) => {},
                    "",
                );
            };

            const cardClass = computed(() => {
                return `node-color-${nodeNote.value.color}`;
            });

            onMounted(() => {
                nodeNote.value = props.nodeNoteInitial;
                getNote();
            });

            function getNote() {
                doGet(
                    props.noteUrl,
                    (response) => {
                        note.value = response.data;
                        noteContents.value = response.data.content;
                    },
                    "Error getting note",
                );
            };

            return {
                action,
                cardClass,
                colors,
                editableTextArea,
                getClass,
                getNote,
                handleNameEdit,
                handleNameEdit,
                handleNoteDelete,
                handleNoteEdit,
                isEditingName,
                onOpenNoteMetadataModal,
                nodeNote,
                note,
                noteContents,
                editNoteContents,
                editNoteMetadata,
            };
        },
    };

</script>

// bordercore/front-end/react/node/NodeNote.tsx
import React, { useState, useEffect, useRef } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faStickyNote, faPencilAlt, faTimes } from "@fortawesome/free-solid-svg-icons";
import { Card } from "../common/Card";
import { DropDownMenu } from "../common/DropDownMenu";
import { doGet, doPost, doPut } from "../utils/reactUtils";
import type { NoteLayoutItem, Note, NodeColor } from "./types";

interface NodeNoteProps {
  nodeUuid: string;
  noteInitial: NoteLayoutItem;
  noteUrl: string;
  setNoteColorUrl: string;
  deleteNoteUrl: string;
  colorPreview?: NodeColor;
  onOpenNoteMetadataModal: (
    callback: (data: { name: string; color: NodeColor }) => void,
    data: { name: string; color: NodeColor; uuid: string }
  ) => void;
  onEditLayout: (layout: string) => void;
}

export default function NodeNote({
  nodeUuid,
  noteInitial,
  noteUrl,
  setNoteColorUrl,
  deleteNoteUrl,
  colorPreview,
  onOpenNoteMetadataModal,
  onEditLayout,
}: NodeNoteProps) {
  const [nodeNote, setNodeNote] = useState<NoteLayoutItem>(noteInitial);
  const [note, setNote] = useState<Note | null>(null);
  const [noteContents, setNoteContents] = useState("");
  const [isEditingName, setIsEditingName] = useState(false);
  const [isEditingContent, setIsEditingContent] = useState(false);
  const nameInputRef = useRef<HTMLInputElement>(null);
  const contentTextareaRef = useRef<HTMLTextAreaElement>(null);
  const nameCacheRef = useRef<string | null>(null);

  useEffect(() => {
    getNote();
  }, []);

  useEffect(() => {
    if (isEditingName && nameInputRef.current) {
      nameInputRef.current.focus();
    }
  }, [isEditingName]);

  useEffect(() => {
    if (isEditingContent && contentTextareaRef.current) {
      contentTextareaRef.current.focus();
    }
  }, [isEditingContent]);

  const getNote = () => {
    doGet(
      noteUrl,
      response => {
        setNote(response.data);
        setNoteContents(response.data.content || "");
      },
      "Error getting note"
    );
  };

  const editNoteContents = () => {
    doPut(
      noteUrl,
      {
        uuid: nodeNote.uuid,
        name: nodeNote.name,
        content: noteContents,
        is_note: "true",
      },
      () => {},
      ""
    );
  };

  const editNoteMetadata = (data: { name: string; color: NodeColor }) => {
    doPost(
      setNoteColorUrl,
      {
        node_uuid: nodeUuid,
        note_uuid: nodeNote.uuid,
        color: data.color.toString(),
      },
      () => {
        setNodeNote(prev => ({ ...prev, color: data.color, name: data.name }));
      },
      "",
      ""
    );
    editNoteContents();
  };

  const handleNoteEdit = () => {
    setIsEditingContent(true);
  };

  const handleNameDoubleClick = () => {
    nameCacheRef.current = nodeNote.name;
    setIsEditingName(true);
  };

  const handleNameBlur = () => {
    setIsEditingName(false);
    if (nameCacheRef.current === nodeNote.name) {
      return;
    }
    editNoteMetadata({ name: nodeNote.name, color: nodeNote.color });
  };

  const handleContentBlur = () => {
    setIsEditingContent(false);
    editNoteContents();
  };

  const handleNoteDelete = () => {
    doPost(
      deleteNoteUrl,
      {
        node_uuid: nodeUuid,
        note_uuid: note?.uuid || nodeNote.uuid,
      },
      response => {
        onEditLayout(response.data.layout);
      },
      "Note deleted"
    );
  };

  const handleOpenNoteMetadataModal = () => {
    onOpenNoteMetadataModal(editNoteMetadata, {
      name: nodeNote.name,
      color: nodeNote.color,
      uuid: nodeNote.uuid,
    });
  };

  const dropdownContent = (
    <ul className="dropdown-menu-list">
      <li>
        <a
          href="#"
          className="dropdown-menu-item"
          onClick={e => {
            e.preventDefault();
            handleNoteEdit();
          }}
        >
          <span className="dropdown-menu-icon">
            <FontAwesomeIcon icon={faPencilAlt} className="text-primary" />
          </span>
          <span className="dropdown-menu-text">Edit note</span>
        </a>
      </li>
      <li>
        <a
          href="#"
          className="dropdown-menu-item"
          onClick={e => {
            e.preventDefault();
            handleOpenNoteMetadataModal();
          }}
        >
          <span className="dropdown-menu-icon">
            <FontAwesomeIcon icon={faPencilAlt} className="text-primary" />
          </span>
          <span className="dropdown-menu-text">Edit note metadata</span>
        </a>
      </li>
      <li>
        <a
          href="#"
          className="dropdown-menu-item"
          onClick={e => {
            e.preventDefault();
            handleNoteDelete();
          }}
        >
          <span className="dropdown-menu-icon">
            <FontAwesomeIcon icon={faTimes} className="text-primary" />
          </span>
          <span className="dropdown-menu-text">Delete note</span>
        </a>
      </li>
    </ul>
  );

  const titleSlot = (
    <div className="card-title d-flex">
      <div className="dropdown-height d-flex">
        <div>
          <FontAwesomeIcon icon={faStickyNote} className="text-primary me-3" />
        </div>
        <div className="w-100">
          {isEditingName ? (
            <input
              ref={nameInputRef}
              className="form-control w-100"
              value={nodeNote.name}
              onChange={e => setNodeNote(prev => ({ ...prev, name: e.target.value }))}
              onBlur={handleNameBlur}
              onKeyDown={e => {
                if (e.key === "Enter") {
                  handleNameBlur();
                }
              }}
            />
          ) : (
            <span onDoubleClick={handleNameDoubleClick} className="cursor-pointer">
              {nodeNote.name}
            </span>
          )}
        </div>
      </div>
      {note && (
        <div className="dropdown-menu-container ms-auto">
          <DropDownMenu dropdownSlot={dropdownContent} />
        </div>
      )}
    </div>
  );

  const displayColor = colorPreview ?? nodeNote.color;
  const cardClass = `backdrop-filter node-color-${displayColor}`;

  return (
    <div className="hover-target">
      <Card cardClassName={cardClass} titleSlot={titleSlot}>
        <hr className="divider" />
        <div className="node-note">
          {isEditingContent ? (
            <textarea
              ref={contentTextareaRef}
              className="form-control"
              value={noteContents}
              onChange={e => setNoteContents(e.target.value)}
              onBlur={handleContentBlur}
              rows={5}
            />
          ) : (
            <div onClick={() => setIsEditingContent(true)} className="cursor-pointer">
              {noteContents || <span className="text-muted">No content</span>}
            </div>
          )}
        </div>
      </Card>
    </div>
  );
}
