// bordercore/front-end/vue/node/NodeNodeModal.vue
<template>
    <div id="modalSelectNode" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 id="myModalLabel" class="modal-title">
                        {{ action }} Node
                    </h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" />
                </div>
                <div class="modal-body">
                    <div v-if="action === 'Add'" class="mb-3">
                        <select-value
                            ref="selectValue"
                            label="name"
                            place-holder="Search nodes"
                            :search-url="searchUrl"
                            @select="handleNodeSelect"
                        >
                        </select-value>
                    </div>
                    <div class="form-section">
                        Options
                    </div>
                    <div class="row mt-3">
                        <label class="col-lg-4 col-form-label" for="inputTitle">Rotate</label>
                        <div class="col-lg-8">
                            <div class="d-flex flex-column">
                                <select v-model="options.rotate" class="form-control form-select">
                                    <option
                                        v-for="option in rotateOptions"
                                        :key="option.value"
                                        :value="option.value"
                                    >
                                        {{ option.display }}
                                    </option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input class="btn btn-primary" type="button" value="Save" @click="handleNodeEdit">
                </div>
            </div>
        </div>
    </div>
</template>

<script>

    import SelectValue from "/front-end/vue/common/SelectValue.vue";

    export default {
        components: {
            SelectValue,
        },
        props: {
            parentNodeUuid: {
                default: "",
                type: String,
            },
            addNodeUrl: {
                default: "",
                type: String,
            },
            searchUrl: {
                default: "",
                type: String,
            },
        },
        emits: ["select-node", "edit-layout"],
        setup(props, ctx) {
            const action = ref("Edit");
            let callback = null;
            let modal = null;
            const optionsDefault = {"rotate": -1};
            const options = ref(optionsDefault);
            let nodeUuid = null;

            const rotateOptions = [
                {
                    value: -1,
                    display: "Never",
                    default: true,
                },
                {
                    value: 1,
                    display: "Every Minute",
                },
                {
                    value: 5,
                    display: "Every 5 Minutes",
                },
                {
                    value: 10,
                    display: "Every 10 Minutes",
                },
                {
                    value: 30,
                    display: "Every 30 Minutes",
                },
                {
                    value: 60,
                    display: "Every Hour",
                },
                {
                    value: 1440,
                    display: "Every Day",
                },
            ];

            const selectValue = ref(null);

            function handleNodeEdit() {
                if (action.value === "Add") {
                    doPost(
                        props.addNodeUrl,
                        {
                            "parent_node_uuid": props.parentNodeUuid,
                            "node_uuid": nodeUuid,
                            "options": JSON.stringify(options.value),
                        },
                        (response) => {
                            ctx.emit("edit-layout", response.data.layout);
                            modal.hide();
                        },
                        "Node created",
                    );
                } else {
                    callback(options.value);
                    modal.hide();
                }
            };

            function handleNodeSelect(node) {
                nodeUuid = node.uuid;
            };

            function openModal(actionParam, callbackParam, optionsParam) {
                action.value = actionParam;
                callback = callbackParam;
                options.value = optionsParam ? optionsParam : optionsDefault;
                modal.show();
                if (action.value === "Add") {
                    setTimeout( () => {
                        document.querySelector("#modalSelectNode input").focus();
                    }, 500);
                }
            };

            onMounted(() => {
                modal = new Modal("#modalSelectNode");
            });

            return {
                action,
                handleNodeSelect,
                handleNodeEdit,
                options,
                openModal,
                rotateOptions,
                selectValue,
            };
        },
    };

</script>

// bordercore/front-end/react/node/NodeNodeModal.tsx
import React, { useState, useEffect, useRef } from "react";
import { Modal } from "bootstrap";
import { SelectValue } from "../common/SelectValue";
import { ROTATE_OPTIONS, type NodeOptions } from "./types";

interface NodeSearchResult {
  uuid: string;
  name: string;
}

interface NodeNodeModalProps {
  isOpen: boolean;
  action: "Add" | "Edit";
  searchUrl: string;
  data: NodeOptions | null;
  onSave: (options: NodeOptions) => void;
  onSelectNode: (nodeUuid: string, options: NodeOptions) => void;
  onClose: () => void;
}

const defaultOptions: NodeOptions = {
  rotate: -1,
};

export default function NodeNodeModal({
  isOpen,
  action,
  searchUrl,
  data,
  onSave,
  onSelectNode,
  onClose,
}: NodeNodeModalProps) {
  const [options, setOptions] = useState<NodeOptions>(defaultOptions);
  const [selectedNodeUuid, setSelectedNodeUuid] = useState<string | null>(null);

  const modalRef = useRef<HTMLDivElement>(null);
  const modalInstanceRef = useRef<Modal | null>(null);

  useEffect(() => {
    if (modalRef.current && !modalInstanceRef.current) {
      modalInstanceRef.current = new Modal(modalRef.current);

      modalRef.current.addEventListener("hidden.bs.modal", () => {
        onClose();
      });
    }
  }, [onClose]);

  useEffect(() => {
    if (isOpen) {
      setOptions(data || defaultOptions);
      setSelectedNodeUuid(null);
    }
  }, [isOpen, data]);

  useEffect(() => {
    if (modalInstanceRef.current) {
      if (isOpen) {
        modalInstanceRef.current.show();
        // Focus the search input after modal opens
        setTimeout(() => {
          const input = modalRef.current?.querySelector("#modalSelectNode input") as HTMLInputElement;
          if (input && action === "Add") {
            input.focus();
          }
        }, 500);
      } else {
        modalInstanceRef.current.hide();
      }
    }
  }, [isOpen, action]);

  const handleNodeSelect = (node: NodeSearchResult) => {
    setSelectedNodeUuid(node.uuid);
  };

  const handleSave = () => {
    if (action === "Add" && selectedNodeUuid) {
      onSelectNode(selectedNodeUuid, options);
    } else if (action === "Edit") {
      onSave(options);
    }
    modalInstanceRef.current?.hide();
  };

  return (
    <div
      ref={modalRef}
      className="modal fade"
      id="modalSelectNode"
      tabIndex={-1}
      role="dialog"
      aria-labelledby="myModalLabel"
    >
      <div className="modal-dialog" role="document">
        <div className="modal-content">
          <div className="modal-header">
            <h4 className="modal-title" id="myModalLabel">
              {action} Node
            </h4>
            <button
              type="button"
              className="btn-close"
              data-bs-dismiss="modal"
              aria-label="Close"
            />
          </div>
          <div className="modal-body">
            {action === "Add" && (
              <div className="mb-3">
                <SelectValue
                  label="name"
                  placeHolder="Search nodes"
                  searchUrl={searchUrl}
                  onSelect={handleNodeSelect}
                />
              </div>
            )}
            <div className="form-section">Options</div>
            <div className="row mt-3">
              <label className="col-lg-4 col-form-label" htmlFor="inputRotate">
                Rotate
              </label>
              <div className="col-lg-8">
                <div className="d-flex flex-column">
                  <select
                    id="inputRotate"
                    className="form-control form-select"
                    value={options.rotate}
                    onChange={(e) =>
                      setOptions((prev) => ({
                        ...prev,
                        rotate: parseInt(e.target.value, 10),
                      }))
                    }
                  >
                    {ROTATE_OPTIONS.map((opt) => (
                      <option key={opt.value} value={opt.value}>
                        {opt.display}
                      </option>
                    ))}
                  </select>
                </div>
              </div>
            </div>
          </div>
          <div className="modal-footer">
            <input
              className="btn btn-primary"
              type="button"
              value="Save"
              onClick={handleSave}
            />
          </div>
        </div>
      </div>
    </div>
  );
}
