// bordercore/front-end/react/drill/DrillDisabledTags.tsx
import React, { useState, useEffect, useRef, useCallback } from "react";
import { Modal } from "bootstrap";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faTimesCircle, faEllipsisV, faPencilAlt } from "@fortawesome/free-solid-svg-icons";
import Card from "../common/Card";
import DropDownMenu from "../common/DropDownMenu";
import SelectValue, { SelectValueHandle } from "../common/SelectValue";
import { doGet, doPost } from "../utils/reactUtils";

interface DisabledTag {
  name: string;
  url: string;
  progress: number;
  count: number;
  last_reviewed: string;
}

interface DrillDisabledTagsProps {
  getDisabledTagsUrl: string;
  disableTagUrl: string;
  enableTagUrl: string;
  tagSearchUrl: string;
}

export function DrillDisabledTags({
  getDisabledTagsUrl,
  disableTagUrl,
  enableTagUrl,
  tagSearchUrl,
}: DrillDisabledTagsProps) {
  const [dataLoading, setDataLoading] = useState(true);
  const [tagList, setTagList] = useState<DisabledTag[]>([]);

  const selectValueRef = useRef<SelectValueHandle>(null);
  const modalRef = useRef<HTMLDivElement>(null);
  const modalInstanceRef = useRef<Modal | null>(null);

  const getTagList = useCallback(() => {
    doGet(
      getDisabledTagsUrl,
      (response: any) => {
        setTagList(response.data.tag_list);
        setDataLoading(false);
      },
      "Error getting disabled tags"
    );
  }, [getDisabledTagsUrl]);

  useEffect(() => {
    getTagList();
  }, [getTagList]);

  useEffect(() => {
    if (modalRef.current && !modalInstanceRef.current) {
      modalInstanceRef.current = new Modal(modalRef.current);
    }
  }, []);

  const handleTagDisable = useCallback(
    (tag: string) => {
      doPost(disableTagUrl, { tag }, () => {
        getTagList();
      });
    },
    [disableTagUrl, getTagList]
  );

  const handleTagEnable = useCallback(
    (tagName: string) => {
      doPost(enableTagUrl, { tag: tagName }, () => {
        getTagList();
      });
    },
    [enableTagUrl, getTagList]
  );

  const handleTagSelect = useCallback(
    (selection: any) => {
      handleTagDisable(selection.label || selection.name);
    },
    [handleTagDisable]
  );

  const openModal = useCallback(() => {
    if (modalInstanceRef.current) {
      modalInstanceRef.current.show();
      setTimeout(() => {
        selectValueRef.current?.focus();
      }, 500);
    }
  }, []);

  const titleSlot = (
    <div className="card-title d-flex align-items-center">
      <div>Disabled Tags</div>
      <div className="ms-auto">
        <DropDownMenu
          iconSlot={<FontAwesomeIcon icon={faEllipsisV} />}
          dropdownSlot={
            <ul className="dropdown-menu-list">
              <li key="manage">
                <a
                  className="dropdown-item"
                  href="#"
                  onClick={e => {
                    e.preventDefault();
                    openModal();
                  }}
                >
                  <FontAwesomeIcon icon={faPencilAlt} className="text-primary me-3" />
                  Manage
                </a>
              </li>
            </ul>
          }
        />
      </div>
    </div>
  );

  return (
    <div className="d-flex flex-grow-1">
      {/* Modal for managing disabled tags */}
      <div ref={modalRef} id="modalDisabledTags" className="modal fade" tabIndex={-1} role="dialog">
        <div className="modal-dialog" role="document">
          <div className="modal-content">
            <div className="modal-header">
              <h4 id="myModalLabel" className="modal-title">
                Disabled Tags
              </h4>
              <button type="button" className="close-button btn-close" data-bs-dismiss="modal" />
            </div>
            <div className="modal-body">
              <div className="form-row align-items-center">
                <div className="form-row mx-1 w-100">
                  <SelectValue
                    ref={selectValueRef}
                    searchUrl={`${tagSearchUrl}?doctype=drill&query=`}
                    placeHolder="Search Tag"
                    onSelect={handleTagSelect}
                  />
                </div>
              </div>
              <ul id="drill-pinned-tags" className="interior-borders p-2 mb-0 wide-list">
                <div className="slicklist-list-item-inner">
                  {tagList.map(tag => (
                    <li key={tag.name} className="list-group-item px-2 py-1">
                      <div className="d-flex">
                        <div>{tag.name}</div>
                        <div className="ms-auto my-auto">
                          <FontAwesomeIcon
                            icon={faTimesCircle}
                            className="list-delete cursor-pointer"
                            onClick={() => handleTagEnable(tag.name)}
                          />
                        </div>
                      </div>
                    </li>
                  ))}
                </div>
              </ul>
            </div>
            <div className="modal-footer justify-content-start">
              <input
                className="btn btn-primary"
                type="button"
                value="Save"
                data-bs-dismiss="modal"
              />
            </div>
          </div>
        </div>
      </div>

      {/* Card component */}
      <Card
        className="backdrop-filter hover-target flex-grow-1"
        cardClassName="flex-grow-1"
        titleSlot={titleSlot}
      >
        <hr className="divider" />
        {dataLoading ? (
          <div className="text-secondary">Data Loading...</div>
        ) : (
          <ul className="list-unstyled">
            {tagList.map(tag => (
              <li key={tag.name} className="d-flex px-2">
                <div className="item-name flex-fill">
                  <a href={`${tag.url}?filter=review`}>{tag.name}</a>
                </div>
                <div className="item-value">{tag.progress}%</div>
              </li>
            ))}
            {tagList.length === 0 && (
              <li key="add-tag">
                <a
                  href="#"
                  onClick={e => {
                    e.preventDefault();
                    openModal();
                  }}
                >
                  Add a tag
                </a>
              </li>
            )}
          </ul>
        )}
      </Card>
    </div>
  );
}

export default DrillDisabledTags;

// bordercore/front-end/vue/drill/DrillDisabledTags.vue
<template>
    <div class="d-flex h-100">
        <div id="modalDisabledTags" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 id="myModalLabel" class="modal-title">
                            Disabled Tags
                        </h4>
                        <button type="button" class="close-button btn-close" data-bs-dismiss="modal" />
                    </div>
                    <div class="modal-body">
                        <div class="form-row align-items-center">
                            <div class="form-row mx-1 w-100">
                                <select-value
                                    ref="selectValuePinnedTag"
                                    :search-url="tagSearchUrl + '?doctype=drill&query='"
                                    place-holder="Search Tag"
                                    @select="handleTagSelect"
                                />
                            </div>
                        </div>
                        <ul id="drill-pinned-tags" class="interior-borders p-2 mb-0 wide-list">
                            <div class="slicklist-list-item-inner">
                                <li v-for="tag in tagList" :key="tag.name" class="list-group-item px-2 py-1">
                                    <div class="d-flex">
                                        <div>
                                            {{ tag.name }}
                                        </div>
                                        <div class="ms-auto my-auto">
                                            <font-awesome-icon icon="times-circle" class="list-delete" @click="handleTagEnable(tag.name)" />
                                        </div>
                                    </div>
                                </li>
                            </div>
                        </ul>
                    </div>
                    <div class="modal-footer justify-content-start">
                        <input class="btn btn-primary" type="button" value="Save" data-bs-dismiss="modal">
                    </div>
                </div>
            </div>
        </div>
        <card
            id="vue-app-pinned-tags"
            title="Disabled Tags"
            class="backdrop-filter hover-target flex-grow-1"
        >
            <template #title-slot>
                <div class="card-title d-flex align-items-center">
                    <div>
                        Disabled Tags
                    </div>
                    <drop-down-menu :show-on-hover="true">
                        <font-awesome-icon icon="ellipsis-v" />
                        <template #dropdown>
                            <li>
                                <a class="dropdown-item" href="#" @click="openModal()">
                                    <font-awesome-icon icon="pencil-alt" class="text-primary me-3" />
                                    Manage
                                </a>
                            </li>
                        </template>
                    </drop-down-menu>
                </div>
            </template>
            <template #content>
                <hr class="divider">
                <div v-if="dataLoading" class="text-secondary">
                    Data Loading...
                </div>
                <ul v-else class="list-unstyled">
                    <li v-for="tag in tagList" :key="tag.name" class="d-flex px-2">
                        <div class="item-name flex-fill">
                            <a :href="tag.url + '?filter=review'">{{ tag.name }}</a>
                        </div>
                        <div class="item-value">
                            {{ tag.progress }}%
                        </div>
                    </li>
                    <li v-if="!tagList.length">
                        <a href="#" @click="openModal()">Add a tag</a>
                    </li>
                </ul>
            </template>
        </card>
    </div>
</template>

<script>

    import Card from "/front-end/vue/common/Card.vue";
    import DropDownMenu from "/front-end/vue/common/DropDownMenu.vue";
    import {FontAwesomeIcon} from "@fortawesome/vue-fontawesome";
    import SelectValue from "/front-end/vue/common/SelectValue.vue";

    export default {
        components: {
            Card,
            DropDownMenu,
            FontAwesomeIcon,
            SelectValue,
        },
        props: {
            getDisabledTagsUrl: {
                default: "",
                type: String,
            },
            disableTagUrl: {
                default: "",
                type: String,
            },
            enableTagUrl: {
                default: "",
                type: String,
            },
            sortPinnedTagsUrl: {
                default: "",
                type: String,
            },
            tagSearchUrl: {
                default: "",
                type: String,
            },
        },
        setup(props) {
            const dataLoading = ref(true);
            const selectValuePinnedTag = ref(null);
            const tagList = ref([]);

            function getTagList() {
                doGet(
                    props.getDisabledTagsUrl,
                    (response) => {
                        tagList.value = response.data.tag_list;
                        dataLoading.value = false;
                    },
                    "Error getting disabled tags",
                );
            };

            function handleTagDisable(tag) {
                doPost(
                    props.disableTagUrl,
                    {
                        "tag": tag,
                    },
                    () => {
                        getTagList();
                    },
                );
            };

            function handleTagEnable(tagName) {
                doPost(
                    props.enableTagUrl,
                    {
                        "tag": tagName,
                    },
                    () => {
                        getTagList();
                    },
                );
            };

            function handleTagSelect(selection) {
                handleTagDisable(selection.info.name);

                nextTick(() => {
                    selectValuePinnedTag.value.clearOptions();
                });
            };

            function openModal() {
                const modal = new Modal("#modalDisabledTags");
                modal.show();
                setTimeout(() => {
                    selectValuePinnedTag.value.focus();
                }, 500);
            };

            onMounted(() => {
                getTagList();
            });

            return {
                dataLoading,
                handleTagEnable,
                handleTagSelect,
                openModal,
                selectValuePinnedTag,
                tagList,
            };
        },
    };

</script>
